### PR TITLE
don't use menpo channel for opencv

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by neurolabusc** [comment]
@isuruf the `conda install -c menpo opencv` was suggested in [issue 2](https://github.com/neurolabusc/AppleSiliconForNeuroimaging/issues/2). As I noted in my response there, this is outside my expertise. Would you mind explaining the difference with including the `menpo` channel.

@HarryOC493 are you happy to sign off on the proposed change. Can you validate that the `conda install opencv` command works on your system.

**Comment by isuruf** [comment]
`menpo` is a custom channel that has really old opencv packages (and no native apple silicon packages) and it shouldn't be needed as the default channel has the opencv packages

**Comment by neurolabusc** [comment]
Thanks. That makes sense, and explains my observation of slow first start time mentioned in my comment to issue 2. I just tried the command `conda install opencv` and it does seem compatible with the [AppleSilicon native Python distribution](https://github.com/conda-forge/miniforge#download) I am using. 

@HarryOC493 with your consent I will merge this pull request.

**Comment by HarryOC493** [comment]
@neurolabusc  Yeah u have my consent, although @isuruf I did try using the standard non-menpo channel but no matter what I used to try install it I always got a an error along the lines of Error Expected Flat Namespace, but if it worked for you that was probably a niche issue for me.

**Comment by isuruf** [comment]
@HarryOC493, please open an issue in https://github.com/conda-forge/opencv-feedstock/issues if you are using conda-forge's miniforge distribution.

**Comment by neurolabusc** [comment]
@HarryOC493 the command `conda install opencv` worked for me. I downloaded the native [conda distribution](https://github.com/conda-forge/miniforge#download) suggested by this repository. Maybe you can replicate the commands below to 
 1. Determine the path to the Python you are using and reveal the distribution (e.g. miniforge)
 2. Use file to ensure you installed the native arm64 version rather than the translated (arm64e) version.
 3. Determine the version of Python you are using, e.g. 3.9.1


$ which python       
/Users/chrisrorden/miniforge3/bin/python
$ file /Users/chrisrorden/miniforge3/bin/python
/Users/chrisrorden/miniforge3/bin/python: Mach-O 64-bit executable arm64
$ python &
[1] 16888
AppleSiliconForNeuroimaging > Python 3.9.1 | packaged by conda-forge | (default, Dec  9 2020, 01:07:47)

**Comment by HarryOC493** [comment]
Yeah I think I just had configured it weirdly, messing around and all. Feel free to commit this u have my consent

**Comment by HarryOC493** [comment]
@neurolabusc I had to install opencv in a new conda env (don't ask) and the command u sent "conda install opencv" worked perfectly

**Pull request merged**
